source: src
paths:
  uploads: assets/uploads/:title
  static: ''
data_config:
  fonts:
    path: _data/fonts.json
  authors:
    path: _data/authors.json
  blogTags:
    path: _data/blogTags.json
  reviews:
    path: _data/reviews.yml
  blog:
    path: _data/blog.json
  happenings:
    path: _data/happenings.yml
collections_config_override: true
collections_config:
  data:
    path: _data
    icon: settings
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: pages
    output: true
    glob:
      - '!robots.njk'
      - '!rss.njk'
      - '!sitemap.njk'
      - '!tags.md'
      - '!pages.json'
      - '!404.md'
    name: Pages
    description: All your pages
    icon: description
    documentation: null
    preview:
      gallery: description
    sort: null
    sort_options: null
    singular_name: null
    singular_key: null
    _editables: null
    _enabled_editors:
      - content
      - visual
    _inputs:
      title:
        label: Page Title
        comment: Seo focused page title
      removeFromNavigation:
        type: switch
        label: Remove from navigation
        comment: Will remove this page from top navigation top nav and footer
      eleventyExcludeFromCollections:
        hidden: true
      eleventyNavigation:
        label: Navigation
      eleventyNavigation.key:
        comment: How this page is identified in the navigation
      eleventyNavigation.order:
        comment: What order in the navigation
      eleventyNavigation.title:
        label: Display Title
        comment: >-
          What website visitors will see. Leave blank if you want to use the key
          as Display Title
      eleventyNavigation.parent:
        comment: What key this should be grouped with. Leave blank for no grouping
      eleventyNavigation.url:
        label: External Link
        comment: >-
          If you want to have a link to another website or file on your site,
          place that link here. Leave blank for all other situations. WARNING:
          this will prevent this page from building and showing up in your
          website.
      pageLink:
        label: Page Location
        comment: The location of this page on your webiste i.e. Example.com/mylocation. Leave blank if you want to just use the page title as the page location.
        type: text
      metaDesc:
        type: textarea
        label: Meta Description
        comment: SEO focused page summary
      permalink:
        hidden: true
      pagination:
        hidden: true
      layout:
        hidden: true
    _select_data: null
    _structures: null
    add_options: null
    create: null
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: null
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
    schema_key: null
  blog:
    path: posts
    output: true
    glob:
      - '!posts.json'
    _enabled_editors:
      - content
    _inputs:
      title:
        label: Page Title
        comment: Seo focused page title
      metaDesc:
        type: textarea
        label: Meta Description
        comment: SEO focused page summary
      author:
        type: select
        options:
          values: data.authors
          value_key: id
          text_key: name
      tags:
        type: multiselect
        options:
          values: data.blogTags
      date:
        type: date
        label: Published Date
        instance_value: NOW
      happening:
        type: switch
        label: Make into a happening
        comment: Turn this post into a happening
      cancelled:
        hidden: '!happening'
      happeningDate:
        hidden: '!happening'
        type: datetime
        label: Happening Date
        comment: >-
          If this blog post is tagged with a happening tag, enter the happening date here. If not, leave blank.
          IMPORTANT: The date must be in UTC time. You'll need to convert your local time to UTC time.
      summary:
        hidden: '!happening'
        type: textarea
        label: Happening Summary
        comment: A short summary of the happening.
      image:
        hidden: true
      permalink:
        hidden: true
      socialImage:
        hidden: true
      eleventyExcludeFromCollections:
        hidden: true
    schemas:
      default:
        path: .cloudcannon/schemas/post.md
  happenings:
    path: happenings
    output: true
    icon: event
    glob:
      - '!happenings.json'
    _enabled_editors:
      - content
      - visual
    _inputs:
      title:
        label: Page Title
        comment: Seo focused page title
      metaDesc:
        type: textarea
        label: Meta Description
        comment: SEO focused page summary
      tags:
        type: multiselect
        options:
          values: data.blogTags
      summary:
        type: textarea
      happeningDate:
        type: datetime
        label: Happening Date
        comment: >-
          IMPORTANT: The date must be in UTC time. You'll need to convert your local time to UTC time.
        instance_value: NOW
      image:
        hidden: true
      permalink:
        hidden: true
      socialImage:
        hidden: true
      eleventyExcludeFromCollections:
        hidden: true
    schemas:
      default:
        path: .cloudcannon/schemas/happening.md
  services:
    path: services
    output: true
    name: Services
    description: All your services
    icon: design_services
    documentation: null
    preview:
      gallery: design_services
    glob:
      - '!services.json'
    _inputs:
      title:
        label: Page Title
        comment: Seo focused page title
      metaDesc:
        type: textarea
        label: Meta Description
        comment: SEO focused page summary
      category:
        type: text
        comment: >-
          The category of the service, used to group services together. If no
          category is specified, the service will be given a cateory of
          "Services"
      categorySlug:
        hidden: true
      summary:
        type: textarea
        comment: A short summary of the service
      permalink:
        hidden: true
      eleventyExcludeFromCollections:
        hidden: true
    schemas:
      default:
        path: .cloudcannon/schemas/service.md
_inputs:
  pagination:
    hidden: true
  layout:
    hidden: true
  blogCards:
    type: object
    options:
      structures: _structures.blog_cards
  hero:
    type: object
    options:
      structures: _structures.hero_blocks
  description:
    type: markdown
    options:
      link: true
      bold: true
      italic: true
      undo: true
      redo: true
      initial_height: 135
  socialImage:
    type: image
    hidden: false
  color_group:
    type: select
    options:
      allow_empty: false
      value_key: id
      preview:
        text:
          - key: name
        icon:
          - key: icon
      values:
        - id: primary
          name: Primary
        - &ref_0
          name: Primary Dark
          id: primary_dark0
  nav_color_group:
    type: select
    options:
      allow_empty: false
      value_key: id
      preview:
        text:
          - key: name
        icon:
          - key: icon
      values:
        - id: primary
          name: Primary
        - *ref_0
  footer_color_group:
    type: select
    options:
      allow_empty: false
      value_key: id
      preview:
        text:
          - key: name
        icon:
          - key: icon
      values:
        - id: primary
          name: Primary
        - *ref_0
  card_color_group:
    type: select
    options:
      allow_empty: false
      value_key: id
      preview:
        text:
          - key: name
        icon:
          - key: icon
      values:
        - id: primary
          name: Primary
        - *ref_0
  form_color_group:
    type: select
    options:
      allow_empty: false
      value_key: id
      preview:
        text:
          - key: name
        icon:
          - key: icon
      values:
        - id: primary
          name: Primary
        - *ref_0
  id:
    hidden: true
    instance_value: UUID
  arrangement:
    type: select
    comment: The layout of the icon and text together
    options:
      values:
        - name: Inline
          id: inline
        - name: Stacked
          id: stacked
  sectionId:
    comment: >-
      An ID given to a section to be able to link to it Example:
      example.com/#sectionId where sectionID is what you type in this box
  font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here. Note: fonts needs to have at least style 400 and 700
      available
    type: select
    options:
      values: data.fonts
  heading_font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here. Note: fonts needs to have at least style 400 and 700
      available
    type: select
    options:
      values: data.fonts
  content_font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here. Note: fonts needs to have at least style 400 and 700
      available
    type: select
    options:
      values: data.fonts
  logo_font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here. Note: fonts needs to have at least style 400 and 700
      available
    type: select
    options:
      values: data.fonts
  showNote:
    type: switch
    comment: >-
      Hide/Show the note that contains helpful information about the live
      editing of this component. This note doesn't show up on the live site.
  service:
    type: select
    options:
      values: collections.services
      value_key: id
      text_key: title
  colorFromGroup:
    type: select
    options:
      allow_empty: false
      value_key: id
      values:
        - id: text
          name: Text
        - id: background
          name: Background
        - id: primary
          name: Primary
        - id: secondary
          name: Secondary
        - id: accent
          name: Accent
  review:
    type: textarea
_snippets:
  custom_snippet:
    template: eleventy_liquid_bookshop_component
    inline: false
    preview:
      text: Image
    definitions:
      component_name: snippets/imageModal
      named_args:
        - editor_key: imagePath
          type: string
        - editor_key: imageAlt
          type: string
_select_data: {}
_structures:
  content_blocks:
    style: modal
_editables: {}
timezone: Etc/UTC
